- name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: 18
      cache: 'npm'

  # STREAMING_CHUNK:Instalasi dependensi dan memasukkan variabel rahasia...
  - name: Install Dependensi
    run: npm install

  - name: Build Aplikasi (Vite)
    # Menarik variabel URL dari GitHub Variables agar dikenali saat proses build
    env:
      VITE_GAS_WEB_APP_URL: ${{ vars.VITE_GAS_WEB_APP_URL }}
    run: npm run build

  # STREAMING_CHUNK:Upload dan Deploy ke GitHub Pages...
  - name: Setup GitHub Pages
    uses: actions/configure-pages@v4

  - name: Upload Artifact
    uses: actions/upload-pages-artifact@v3
    with:
      path: './dist'

  - name: Deploy ke GitHub Pages
    id: deployment
    uses: actions/deploy-pages@v4
